/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PrivatePluginHubPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  registryUrl: "http://localhost:8888/hub/registry.json",
  autoCheckUpdates: true,
  showExperimental: false
};

// src/views/MarketModal.ts
var import_obsidian3 = require("obsidian");

// src/services/RegistryService.ts
var import_obsidian = require("obsidian");
var RegistryService = class {
  constructor(app) {
    this.app = app;
  }
  /**
   * Fetch the remote registry manifest
   */
  async fetchRegistry(registryUrl) {
    if (!registryUrl) {
      throw new Error("Registry URL is not configured.");
    }
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: registryUrl,
        method: "GET",
        headers: {
          "Cache-Control": "no-cache",
          "Pragma": "no-cache"
        }
      });
      if (response.status !== 200) {
        throw new Error(`Failed to fetch registry (HTTP ${response.status})`);
      }
      const data = response.json;
      return data.plugins || [];
    } catch (error) {
      console.error("[PrivatePluginHub] Error fetching registry:", error);
      throw error;
    }
  }
  /**
   * Get local plugin status for a given plugin ID
   */
  getLocalPluginInfo(pluginId) {
    const pluginsApi = this.app.plugins;
    if (!pluginsApi)
      return null;
    const manifests = pluginsApi.manifests || {};
    const enabledPlugins = pluginsApi.enabledPlugins || /* @__PURE__ */ new Set();
    const manifest = manifests[pluginId];
    if (!manifest) {
      return null;
    }
    return {
      id: pluginId,
      manifestVersion: manifest.version,
      enabled: enabledPlugins.has(pluginId)
    };
  }
  /**
   * Determine current installation status of a remote plugin
   */
  getPluginStatus(remotePlugin) {
    const localInfo = this.getLocalPluginInfo(remotePlugin.id);
    if (!localInfo) {
      return "not_installed";
    }
    if (!localInfo.enabled) {
      return "disabled";
    }
    const localVer = localInfo.manifestVersion || "0.0.0";
    const remoteVer = remotePlugin.version || "0.0.0";
    if (this.isVersionNewer(remoteVer, localVer)) {
      return "update_available";
    }
    return "installed";
  }
  /**
   * Compare two version strings (SemVer compliant or string comparison fallback)
   */
  isVersionNewer(remoteVer, localVer) {
    if (remoteVer === localVer)
      return false;
    const cleanRemote = remoteVer.replace(/^v/, "").split(".").map(Number);
    const cleanLocal = localVer.replace(/^v/, "").split(".").map(Number);
    const maxLength = Math.max(cleanRemote.length, cleanLocal.length);
    for (let i = 0; i < maxLength; i++) {
      const r = cleanRemote[i] || 0;
      const l = cleanLocal[i] || 0;
      if (r > l)
        return true;
      if (r < l)
        return false;
    }
    return false;
  }
};

// src/services/InstallerService.ts
var import_obsidian2 = require("obsidian");
var InstallerService = class {
  constructor(app) {
    this.app = app;
  }
  /**
   * Get absolute vault relative path to target plugin folder
   */
  getPluginPath(pluginId) {
    const configDir = this.app.vault.configDir || ".obsidian";
    return `${configDir}/plugins/${pluginId}`;
  }
  /**
   * Download and install or update a custom plugin
   */
  async installOrUpdatePlugin(plugin) {
    const pluginDir = this.getPluginPath(plugin.id);
    const adapter = this.app.vault.adapter;
    try {
      new import_obsidian2.Notice(`Downloading ${plugin.name} v${plugin.version}...`);
      if (!await adapter.exists(pluginDir)) {
        await adapter.mkdir(pluginDir);
      }
      const baseUrl = plugin.url.endsWith("/") ? plugin.url : `${plugin.url}/`;
      const manifestUrl = `${baseUrl}manifest.json?t=${Date.now()}`;
      const manifestRes = await (0, import_obsidian2.requestUrl)({ url: manifestUrl });
      if (manifestRes.status !== 200) {
        throw new Error(`Failed to download manifest.json (HTTP ${manifestRes.status})`);
      }
      await adapter.write(`${pluginDir}/manifest.json`, manifestRes.text);
      const mainJsUrl = `${baseUrl}main.js?t=${Date.now()}`;
      const mainJsRes = await (0, import_obsidian2.requestUrl)({ url: mainJsUrl });
      if (mainJsRes.status !== 200) {
        throw new Error(`Failed to download main.js (HTTP ${mainJsRes.status})`);
      }
      await adapter.write(`${pluginDir}/main.js`, mainJsRes.text);
      try {
        const stylesUrl = `${baseUrl}styles.css?t=${Date.now()}`;
        const stylesRes = await (0, import_obsidian2.requestUrl)({ url: stylesUrl });
        if (stylesRes.status === 200 && stylesRes.text) {
          await adapter.write(`${pluginDir}/styles.css`, stylesRes.text);
        }
      } catch (e) {
      }
      const pluginsApi = this.app.plugins;
      if (pluginsApi) {
        await pluginsApi.loadManifests();
        if (pluginsApi.enabledPlugins && pluginsApi.enabledPlugins.has(plugin.id)) {
          new import_obsidian2.Notice(`Reloading ${plugin.name}...`);
          await pluginsApi.disablePluginAndSave(plugin.id);
          await pluginsApi.enablePluginAndSave(plugin.id);
        } else {
          await pluginsApi.enablePluginAndSave(plugin.id);
        }
      }
      new import_obsidian2.Notice(`Successfully installed ${plugin.name} v${plugin.version}!`);
      return true;
    } catch (error) {
      console.error(`[PrivatePluginHub] Installation failed for ${plugin.id}:`, error);
      new import_obsidian2.Notice(`Failed to install ${plugin.name}: ${error.message}`);
      return false;
    }
  }
  /**
   * Enable plugin
   */
  async enablePlugin(pluginId) {
    const pluginsApi = this.app.plugins;
    if (pluginsApi) {
      await pluginsApi.enablePluginAndSave(pluginId);
      new import_obsidian2.Notice(`Enabled plugin: ${pluginId}`);
    }
  }
  /**
   * Disable plugin
   */
  async disablePlugin(pluginId) {
    const pluginsApi = this.app.plugins;
    if (pluginsApi) {
      await pluginsApi.disablePluginAndSave(pluginId);
      new import_obsidian2.Notice(`Disabled plugin: ${pluginId}`);
    }
  }
  /**
   * Uninstall plugin
   */
  async uninstallPlugin(pluginId) {
    const pluginsApi = this.app.plugins;
    const pluginDir = this.getPluginPath(pluginId);
    const adapter = this.app.vault.adapter;
    try {
      if (pluginsApi && pluginsApi.enabledPlugins.has(pluginId)) {
        await pluginsApi.disablePluginAndSave(pluginId);
      }
      if (await adapter.exists(pluginDir)) {
        await adapter.rmdir(pluginDir, true);
      }
      if (pluginsApi) {
        await pluginsApi.loadManifests();
      }
      new import_obsidian2.Notice(`Uninstalled plugin: ${pluginId}`);
      return true;
    } catch (error) {
      console.error(`[PrivatePluginHub] Uninstall failed for ${pluginId}:`, error);
      new import_obsidian2.Notice(`Failed to uninstall plugin: ${pluginId}`);
      return false;
    }
  }
};

// src/views/MarketModal.ts
var MarketModal = class extends import_obsidian3.Modal {
  constructor(app, settings) {
    super(app);
    this.plugins = [];
    this.filteredPlugins = [];
    this.searchQuery = "";
    this.currentTab = "all";
    this.isLoading = false;
    this.settings = settings;
    this.registryService = new RegistryService(app);
    this.installerService = new InstallerService(app);
  }
  async onOpen() {
    const { contentEl, modalEl } = this;
    modalEl.addClass("private-hub-modal");
    contentEl.empty();
    this.buildHeader(contentEl);
    this.buildControls(contentEl);
    this.listContainerEl = contentEl.createDiv({ cls: "private-hub-plugin-list" });
    await this.loadRegistryData();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
  /**
   * Build top modal header
   */
  buildHeader(parentEl) {
    const headerEl = parentEl.createDiv({ cls: "private-hub-header" });
    const titleContainer = headerEl.createDiv({ cls: "private-hub-title-container" });
    const iconEl = titleContainer.createDiv({ cls: "private-hub-title-icon" });
    (0, import_obsidian3.setIcon)(iconEl, "layout-grid");
    const textContainer = titleContainer.createDiv();
    textContainer.createEl("h2", { text: "Private Plugin Hub", cls: "private-hub-title" });
    textContainer.createEl("span", {
      text: "Custom internal plugin marketplace for your team",
      cls: "private-hub-subtitle"
    });
    this.statsContainerEl = headerEl.createDiv({ cls: "private-hub-stats" });
  }
  /**
   * Build search bar, tabs, and action buttons
   */
  buildControls(parentEl) {
    const controlsEl = parentEl.createDiv({ cls: "private-hub-controls" });
    const searchWrapper = controlsEl.createDiv({ cls: "private-hub-search-wrapper" });
    const searchIcon = searchWrapper.createDiv({ cls: "private-hub-search-icon" });
    (0, import_obsidian3.setIcon)(searchIcon, "search");
    this.searchInputEl = searchWrapper.createEl("input", {
      type: "text",
      placeholder: "Search plugins or authors...",
      cls: "private-hub-search-input"
    });
    this.searchInputEl.addEventListener("input", (e) => {
      this.searchQuery = e.target.value.toLowerCase();
      this.applyFilters();
    });
    const tabsEl = controlsEl.createDiv({ cls: "private-hub-tabs" });
    const tabs = [
      { id: "all", label: "All Plugins" },
      { id: "installed", label: "Installed" },
      { id: "updates", label: "Updates" }
    ];
    tabs.forEach((tab) => {
      const tabBtn = tabsEl.createEl("button", {
        text: tab.label,
        cls: `private-hub-tab ${this.currentTab === tab.id ? "is-active" : ""}`
      });
      tabBtn.addEventListener("click", () => {
        tabsEl.querySelectorAll(".private-hub-tab").forEach((el) => el.removeClass("is-active"));
        tabBtn.addClass("is-active");
        this.currentTab = tab.id;
        this.applyFilters();
      });
    });
    const actionsEl = controlsEl.createDiv({ cls: "private-hub-actions" });
    const refreshBtn = actionsEl.createEl("button", {
      cls: "mod-neutral private-hub-btn",
      title: "Check for updates"
    });
    (0, import_obsidian3.setIcon)(refreshBtn, "refresh-cw");
    refreshBtn.createSpan({ text: " Refresh" });
    refreshBtn.addEventListener("click", async () => {
      refreshBtn.addClass("is-loading");
      await this.loadRegistryData();
      refreshBtn.removeClass("is-loading");
    });
    this.updateAllBtnEl = actionsEl.createEl("button", {
      cls: "mod-cta private-hub-btn",
      title: "Update all available plugins"
    });
    (0, import_obsidian3.setIcon)(this.updateAllBtnEl, "download-cloud");
    this.updateAllBtnEl.createSpan({ text: " Update All" });
    this.updateAllBtnEl.style.display = "none";
    this.updateAllBtnEl.addEventListener("click", () => this.handleUpdateAll());
  }
  /**
   * Load registry data from remote server
   */
  async loadRegistryData() {
    this.isLoading = true;
    this.renderLoadingState();
    try {
      this.plugins = await this.registryService.fetchRegistry(this.settings.registryUrl);
      this.applyFilters();
    } catch (error) {
      this.renderErrorState(error.message);
    } finally {
      this.isLoading = false;
    }
  }
  /**
   * Filter plugins based on tab and search query
   */
  applyFilters() {
    const updatesAvailableCount = this.plugins.filter((p) => this.registryService.getPluginStatus(p) === "update_available").length;
    const installedCount = this.plugins.filter((p) => {
      const s = this.registryService.getPluginStatus(p);
      return s === "installed" || s === "update_available" || s === "disabled";
    }).length;
    this.statsContainerEl.setText(`${this.plugins.length} Available | ${installedCount} Installed | ${updatesAvailableCount} Updates`);
    if (updatesAvailableCount > 0) {
      this.updateAllBtnEl.style.display = "inline-flex";
    } else {
      this.updateAllBtnEl.style.display = "none";
    }
    this.filteredPlugins = this.plugins.filter((plugin) => {
      const status = this.registryService.getPluginStatus(plugin);
      if (this.currentTab === "installed" && status === "not_installed") {
        return false;
      }
      if (this.currentTab === "updates" && status !== "update_available") {
        return false;
      }
      if (this.searchQuery) {
        const q = this.searchQuery;
        const matchesName = plugin.name.toLowerCase().includes(q);
        const matchesAuthor = plugin.author.toLowerCase().includes(q);
        const matchesDesc = plugin.description.toLowerCase().includes(q);
        const matchesTags = plugin.tags ? plugin.tags.some((t) => t.toLowerCase().includes(q)) : false;
        return matchesName || matchesAuthor || matchesDesc || matchesTags;
      }
      return true;
    });
    this.renderPluginList();
  }
  /**
   * Render loading state
   */
  renderLoadingState() {
    this.listContainerEl.empty();
    const loader = this.listContainerEl.createDiv({ cls: "private-hub-loading" });
    const spinner = loader.createDiv({ cls: "private-hub-spinner" });
    (0, import_obsidian3.setIcon)(spinner, "loader-2");
    loader.createDiv({ text: "Fetching custom plugins registry..." });
  }
  /**
   * Render error state
   */
  renderErrorState(message) {
    this.listContainerEl.empty();
    const errEl = this.listContainerEl.createDiv({ cls: "private-hub-error" });
    const errIcon = errEl.createDiv({ cls: "private-hub-error-icon" });
    (0, import_obsidian3.setIcon)(errIcon, "alert-triangle");
    errEl.createEl("h4", { text: "Failed to connect to Private Registry" });
    errEl.createEl("p", { text: message });
    errEl.createEl("p", { text: `Target URL: ${this.settings.registryUrl}`, cls: "private-hub-url-hint" });
  }
  /**
   * Render plugin list cards
   */
  renderPluginList() {
    this.listContainerEl.empty();
    if (this.filteredPlugins.length === 0) {
      const emptyEl = this.listContainerEl.createDiv({ cls: "private-hub-empty" });
      (0, import_obsidian3.setIcon)(emptyEl.createDiv({ cls: "private-hub-empty-icon" }), "box");
      emptyEl.createDiv({ text: "No matching plugins found.", cls: "private-hub-empty-text" });
      return;
    }
    const gridEl = this.listContainerEl.createDiv({ cls: "private-hub-grid" });
    this.filteredPlugins.forEach((plugin) => {
      this.renderPluginCard(gridEl, plugin);
    });
  }
  /**
   * Render single plugin card UI
   */
  renderPluginCard(parentEl, plugin) {
    const card = parentEl.createDiv({ cls: "private-hub-card" });
    const status = this.registryService.getPluginStatus(plugin);
    const localInfo = this.registryService.getLocalPluginInfo(plugin.id);
    const cardHeader = card.createDiv({ cls: "private-hub-card-header" });
    const iconContainer = cardHeader.createDiv({ cls: "private-hub-card-icon" });
    (0, import_obsidian3.setIcon)(iconContainer, plugin.icon || "plugin");
    const titleBlock = cardHeader.createDiv({ cls: "private-hub-card-title-block" });
    const titleRow = titleBlock.createDiv({ cls: "private-hub-card-title-row" });
    titleRow.createEl("span", { text: plugin.name, cls: "private-hub-card-title" });
    const metaRow = titleBlock.createDiv({ cls: "private-hub-card-meta" });
    metaRow.createEl("span", { text: `by ${plugin.author}`, cls: "private-hub-author" });
    metaRow.createEl("span", { text: `\u2022  v${plugin.version}`, cls: "private-hub-version" });
    if (status === "update_available") {
      const updateBadge = metaRow.createEl("span", {
        text: `Update to v${plugin.version}`,
        cls: "private-hub-badge badge-update"
      });
      if (localInfo == null ? void 0 : localInfo.manifestVersion) {
        updateBadge.title = `Installed: v${localInfo.manifestVersion}`;
      }
    } else if (status === "installed") {
      metaRow.createEl("span", { text: "Installed", cls: "private-hub-badge badge-installed" });
    } else if (status === "disabled") {
      metaRow.createEl("span", { text: "Disabled", cls: "private-hub-badge badge-disabled" });
    }
    card.createEl("p", { text: plugin.description, cls: "private-hub-card-desc" });
    const cardFooter = card.createDiv({ cls: "private-hub-card-footer" });
    const tagsEl = cardFooter.createDiv({ cls: "private-hub-card-tags" });
    if (plugin.tags && plugin.tags.length > 0) {
      plugin.tags.forEach((tag) => {
        tagsEl.createEl("span", { text: tag, cls: "private-hub-tag" });
      });
    }
    const btnGroup = cardFooter.createDiv({ cls: "private-hub-card-buttons" });
    if (status === "not_installed") {
      const installBtn = btnGroup.createEl("button", {
        text: "Install",
        cls: "mod-cta private-hub-action-btn"
      });
      installBtn.addEventListener("click", async () => {
        installBtn.disabled = true;
        installBtn.setText("Installing...");
        const success = await this.installerService.installOrUpdatePlugin(plugin);
        if (success) {
          this.applyFilters();
        } else {
          installBtn.disabled = false;
          installBtn.setText("Install");
        }
      });
    } else if (status === "update_available") {
      const updateBtn = btnGroup.createEl("button", {
        text: "Update",
        cls: "mod-cta private-hub-action-btn is-update"
      });
      (0, import_obsidian3.setIcon)(updateBtn, "arrow-up-circle");
      updateBtn.createSpan({ text: " Update" });
      updateBtn.addEventListener("click", async () => {
        updateBtn.disabled = true;
        updateBtn.setText("Updating...");
        const success = await this.installerService.installOrUpdatePlugin(plugin);
        if (success) {
          this.applyFilters();
        } else {
          updateBtn.disabled = false;
          updateBtn.setText("Update");
        }
      });
    } else {
      if (status === "disabled") {
        const enableBtn = btnGroup.createEl("button", {
          text: "Enable",
          cls: "mod-cta private-hub-action-btn"
        });
        enableBtn.addEventListener("click", async () => {
          await this.installerService.enablePlugin(plugin.id);
          this.applyFilters();
        });
      } else {
        const disableBtn = btnGroup.createEl("button", {
          text: "Disable",
          cls: "private-hub-action-btn"
        });
        disableBtn.addEventListener("click", async () => {
          await this.installerService.disablePlugin(plugin.id);
          this.applyFilters();
        });
      }
      const uninstallBtn = btnGroup.createEl("button", {
        cls: "mod-warning private-hub-action-btn-icon",
        title: "Uninstall plugin"
      });
      (0, import_obsidian3.setIcon)(uninstallBtn, "trash-2");
      uninstallBtn.addEventListener("click", async () => {
        if (confirm(`Are you sure you want to uninstall ${plugin.name}?`)) {
          await this.installerService.uninstallPlugin(plugin.id);
          this.applyFilters();
        }
      });
    }
  }
  /**
   * Handle Update All action
   */
  async handleUpdateAll() {
    const updatePlugins = this.plugins.filter((p) => this.registryService.getPluginStatus(p) === "update_available");
    if (updatePlugins.length === 0)
      return;
    this.updateAllBtnEl.disabled = true;
    this.updateAllBtnEl.setText("Updating All...");
    let successCount = 0;
    for (const plugin of updatePlugins) {
      const ok = await this.installerService.installOrUpdatePlugin(plugin);
      if (ok)
        successCount++;
    }
    new import_obsidian3.Notice(`Updated ${successCount} / ${updatePlugins.length} plugins!`);
    this.applyFilters();
  }
};

// src/views/SettingTab.ts
var import_obsidian4 = require("obsidian");
var SettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Private Plugin Hub Settings" });
    containerEl.createEl("p", {
      text: "Configure your private/custom plugin repository settings here. Team members can download and update custom plugins hosted on your server.",
      cls: "setting-item-description"
    });
    new import_obsidian4.Setting(containerEl).setName("Registry JSON URL").setDesc("The remote URL pointing to your central registry.json file.").addText((text) => text.setPlaceholder("https://your-server.com/hub/registry.json").setValue(this.plugin.settings.registryUrl).onChange(async (value) => {
      this.plugin.settings.registryUrl = value.trim();
      await this.plugin.saveSettings();
    })).addButton((btn) => btn.setButtonText("Test Connection").setCta().onClick(async () => {
      btn.setButtonText("Testing...");
      btn.setDisabled(true);
      try {
        const registryService = new RegistryService(this.app);
        const plugins = await registryService.fetchRegistry(this.plugin.settings.registryUrl);
        new import_obsidian4.Notice(`Success! Connected to registry with ${plugins.length} plugins.`);
      } catch (e) {
        new import_obsidian4.Notice(`Connection failed: ${e.message}`);
      } finally {
        btn.setButtonText("Test Connection");
        btn.setDisabled(false);
      }
    }));
    new import_obsidian4.Setting(containerEl).setName("Auto Check for Updates").setDesc("Automatically check for updates when Obsidian starts up.").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoCheckUpdates).onChange(async (value) => {
      this.plugin.settings.autoCheckUpdates = value;
      await this.plugin.saveSettings();
    }));
  }
};

// src/main.ts
var PrivatePluginHubPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    const ribbonIconEl = this.addRibbonIcon("layout-grid", "Private Plugin Hub", () => {
      this.openMarketModal();
    });
    ribbonIconEl.addClass("private-plugin-hub-ribbon-class");
    this.addCommand({
      id: "open-private-plugin-hub",
      name: "Open Private Plugin Hub",
      callback: () => {
        this.openMarketModal();
      }
    });
    this.addSettingTab(new SettingTab(this.app, this));
    if (this.settings.autoCheckUpdates && this.settings.registryUrl) {
      this.app.workspace.onLayoutReady(() => {
        this.checkForUpdatesOnStartup();
      });
    }
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  openMarketModal() {
    new MarketModal(this.app, this.settings).open();
  }
  async checkForUpdatesOnStartup() {
    try {
      const service = new RegistryService(this.app);
      const plugins = await service.fetchRegistry(this.settings.registryUrl);
      const updates = plugins.filter((p) => service.getPluginStatus(p) === "update_available");
      if (updates.length > 0) {
        const notice = new import_obsidian5.Notice(
          `Private Plugin Hub: ${updates.length} custom plugin update(s) available! Click to view.`,
          8e3
        );
        notice.noticeEl.style.cursor = "pointer";
        notice.noticeEl.addEventListener("click", () => {
          this.openMarketModal();
        });
      }
    } catch (error) {
      console.debug("[PrivatePluginHub] Startup check error:", error);
    }
  }
};
